name: Keep-Alive System

on:
  push:
    branches: [main]
  schedule:
    # Executa a cada 10 minutos como backup extra
    - cron: "*/10 * * * *"
  workflow_dispatch: # Permite execução manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Test bot (quick run)
        run: |
          timeout 30s python keep_alive_bot.py || true

  # Backup Keep-Alive via GitHub Actions
  backup-ping:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Ping Sites
        run: |
          echo "🔄 GitHub Actions Backup Ping"

          # Lista de sites para manter vivos
          sites=(
            "https://dreamwalkerplane.onrender.com"
            "https://keep-alive-bot-tavl.onrender.com/health"
          )

          for site in "${sites[@]}"; do
            echo "📡 Pingando: $site"
            response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 "$site" || echo "000")
            if [ "$response" -eq 200 ] || [ "$response" -eq 204 ]; then
              echo "✅ $site - OK ($response)"
            else
              echo "⚠️ $site - Falhou ($response)"
            fi
            sleep 5
          done

          echo "🎯 Backup ping concluído via GitHub Actions"
